version: '3.9'

services:
  kotoba_speech:
    build:
      context: .
      dockerfile: Dockerfile
    image: kotoba_speech_image
    volumes:
      - .:/home/user/kotoba_speech_release
    runtime: nvidia  # 追加
    stdin_open: true
    tty: true
    command: >
      /bin/bash -c "
      cd /home/user/kotoba_speech_release &&
      pip install -e . &&
      exec /bin/bash
      "